### ISSUE TITLE
TypeError: Cannot read property 'accountId' of null

### ISSUE THREAD

**Issue by aiwilliams** [JupiterOne/jupiter-integration-jira#15]
Running this against a LifeOmic Jira project getting this error:

```
(node:36743) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
{ error_executing: Unexpected error occurred executing integration! We're looking into it.
    at invokeExecutionHandler (webpack:///./src/integration/execution/invokeExecutionHandler.ts?:25:13)
  _cause:
   TypeError: Cannot read property 'accountId' of null
       at issues.reduce (/Users/aiwilliams/Workspaces/jupiterone-io/jupiter-integration-jira/src/converters/IssueUserRelationshipConverter.ts:43:29)
       at Array.reduce (<anonymous>)
       at Object.createIssueReportedByUserRelationships (/Users/aiwilliams/Workspaces/jupiterone-io/jupiter-integration-jira/src/converters/IssueUserRelationshipConverter.ts:39:17)
       at convertRelationships (/Users/aiwilliams/Workspaces/jupiterone-io/jupiter-integration-jira/src/persister/publishChanges.ts:123:39)
       at convert (/Users/aiwilliams/Workspaces/jupiterone-io/jupiter-integration-jira/src/persister/publishChanges.ts:96:20)
       at Object.publishChanges [as default] (/Users/aiwilliams/Workspaces/jupiterone-io/jupiter-integration-jira/src/persister/publishChanges.ts:34:19)
       at synchronize (/Users/aiwilliams/Workspaces/jupiterone-io/jupiter-integration-jira/src/executionHandler.ts:41:27),
  code: undefined,
  statusCode: undefined,
  expose: true,
  correlationId: undefined,
  name: 'error_executing' }
✨  Done in 8.82s.
```

**Comment by aiwilliams** [comment]
The issue that is failing has these properties:

```js
{
  creator: [Object],
  subtasks: [],
  reporter: null,
}
```

Seems like it may be as simple as coding for the fact that there is not reporter.
